dist: xenial

branches:
  only:
    - develop

addons:
  snaps:
    - name: hugo
      channel: extended

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  repo: ${USERNAME}/${USERNAME}.github.io
  target_branch: master
  on:
    branch: develop
  local_dir: public
  github_token: $GITHUB_TOKEN
  email: $EMAIL
  name: $NAME
  fqdn: blog.harrydev.io
